### PR TITLE
Rider 2020.2 RTM

### PR DESCRIPTION
**Pull request by maartenba**
Support for Rider 2020.2 RTM

### CODE REVIEW

**Comment by grochocki** [comment]
@maartenba Definitely our fault with some of the housekeeping change we made, but we broke CI builds for Rider. I am continuing to investigate, but if you can spot an easy fix, then we can merge the feature branch in and release.

**Comment by maartenba** [comment]
Looking into it, may take a while (because this diverges from the default convention)

**Comment by maartenba** [comment]
Let's wait for CI but I think it's done

**Comment by grochocki** [comment]
Thank you 🙏

**Pull request merged**
