### PR TITLE
External configuration support for Mac extension

### PR DESCRIPTION
**Pull request by Saratsin**
Related to [this issue](https://github.com/Xavalon/XamlStyler/issues/185)
I just don't know is it possible to link issues with pull requests so made by this way.

Now Visual Studio for Mac supports external configuration files "Settings.XamlStyler"

Implements #185 🙂

### CODE REVIEW

**Comment by developering** [comment]
@Saratsin I just installed the latest 1.1.3 version from the MonoDevelop Repo (https://addins.monodevelop.com/Project/Index/382) and I'm seeing a hard error anytime I run XAML styler on Mac. I tried running with a Settings.XamlStyler file in the solution or project, and also without a settings file. Hard error each time.

**Comment by Saratsin** [comment]
@developering what does it mean, hard error? Can you please send a screenshot, or give some detailed explanation?

**Comment by developering** [comment]
Hi @Saratsin, thanks for the quick response!

After installing V1.1.3, running XAMLStyler against any XAML file causes VS for Mac to crash. I see this popup:
Screen Shot 2019-07-10 at 10 39 10 AM

Clicking the More Information button gives me this log, which only has one brief mention of XAMLStyler.
[VSMac-XAMLStyler-error.txt](https://github.com/Xavalon/XamlStyler/files/3378311/VSMac-XAMLStyler-error.txt)

Is the link that I mentioned in my previous comment the correct place from which to install the next version? Maybe I screwed something up there. I downloaded v1.1.3 from that link, uninstalled v1.1.2, and then used option to Install from local file in the Extensions popup to install v1.1.3.

Let me know if there are other details I can send your way. I'm updating to the latest version of VS for Mac right now, just in case that might be the issue.

**Comment by Saratsin** [comment]
@developering can you also provide additional info about Visual Studio version, maybe there could be a problem, here's my version info (on this version v1.1.3 works well):
[AboutVisualStudio.txt](https://github.com/Xavalon/XamlStyler/files/3382225/AboutVisualStudio.txt)

image

**Comment by developering** [comment]
@Saratsin No problem, here are my details:
[AboutVS.txt](https://github.com/Xavalon/XamlStyler/files/3382540/AboutVS.txt)

**Comment by Saratsin** [comment]
@developering I've fixed the problem with Visual Studio crash. You can check it out in the new version, v1.1.4 (already in MonoDevelop Repository, just update your Xaml Styler from Visual Studio extensions window).
I added these changes to this pull request, @grochocki , can you check it again, please?

**Comment by developering** [comment]
@Saratsin I really appreciate you tracking this down. The new version looks great!

**Pull request merged**
