### PR TITLE
Add support for avalonia (.axaml files)

### LINKED ISSUE #320: Add support for avalonia (.axaml) files.
Since avalonia (https://avaloniaui.net) also uses custom XAML files it would be great if this extension is also able to format that files too. 

The only difference is that these files have a different file extension (.axaml instead of .xaml).

I will also create a pull request for this feature.

### PR DESCRIPTION
**Pull request by chkr1011**
### Description:

Fixes #320

Add .axaml files to the document type checking.

### Checklist:
* [x] I have commented my code, particularly in hard-to-understand areas
* [x] My changes generate no new warnings
* [ ] I have added tests that prove my fix is effective or that my feature works
* [x] New and existing unit tests pass locally with my changes
* [ ] I have tested my changes by running the extension in VS2017
* [x] I have tested my changes by running the extension in VS2019
* [x] If changes to the [documentation](https://github.com/Xavalon/XamlStyler/wiki) are needed, I have noted this in the description above

### CODE REVIEW

**Comment by grochocki** [comment]
Thanks for the PR! There are some implementation details about how we want to approach .axaml file support in #300. Would it be possible to update your PR with those changes?

**Comment by chkr1011** [comment]
@grochocki Sure I will update the PR. From what I read the only currently important thing is that the "Selector" attribute should allow the character ">". If there is more to it please let me know.

I will add some "LanguageContext" which will contain information about these escaping stuff per supported language/framework like described in #302.

**Comment by chkr1011** [comment]
@grochocki I added the ability to get some XAML dialect specific options when checking the affected file. Now the > is no longer escaped when an Avalonia file is formatted. I still need to refactor the code a bit but let me know if this is the right way in general.

**Comment by Nickelony** [comment]
Is this still being worked on?

**Comment by Mikolaytis** [comment]
any update on a PR? We are really need an avalonia support!

**Comment by Mikolaytis** [comment]
[XamlStyler.Extension.Windows.vsix.zip](https://github.com/Xavalon/XamlStyler/files/6816531/XamlStyler.Extension.Windows.vsix.zip)
here is VS2019 build of this fork. I've tried. it works. I'm happy now

**Comment by Mikolaytis** [comment]
[XamlStyler.Extension.Windows.VS2022.vsix.zip](https://github.com/Xavalon/XamlStyler/files/7255588/XamlStyler.Extension.Windows.VS2022.vsix.zip)
Here is vs 2022 version if anyone needs it.

**Comment by chkr1011** [comment]
I am basically done with my work. I am still waiting for feedback regarding code style etc.

**Review by Mikolaytis — DISMISSED** [review]

**Review by maxkatz6 — DISMISSED** [review]
As from Avalonia Core team, LGTM.

**Comment by NicoVermeir** [comment]
@maxkatz6 thanks for helping the review from the Avaolonia side of things, greatly appreciated!
@chkr1011 sorry for the (very) long wait, we have looked over your PR and it looks good!
just 2 things:

- could you add unit tests to the PR?
- Can you confirm that this is working in VS2022 as well?

thanks again for your contribution! I'm confident we can merge this in fast

**Comment by chkr1011** [comment]
Sure thing. Please give me a couple of days to do so...

**Comment by chkr1011** [comment]
I added a UnitTests for Avalonia axaml files. Not I still have to test it in VS2022...

**Comment by chkr1011** [comment]
It also works perfectly in VS2022.

**Comment by chkr1011** [comment]
I fixed the build errors but I have no clue how to  fix the Rider Plugin build.

**Comment by chkr1011** [comment]
@NicoVermeir  Is there something missing from my side?

**Comment by NicoVermeir** [comment]
@chkr1011 yes, you've added a new parameter to StylerService. That parameter was missing in the Rider extension.
 I've added it into my own branch but couldn't figure out how to get my change into your PR..
https://github.com/Xavalon/XamlStyler/pull/369

**Comment by chkr1011** [comment]
OK then I will do it manually.

**Comment by chkr1011** [comment]
@NicoVermeir  Now it works 😄

**Review by grochocki — APPROVED** [review]

**Comment by grochocki** [comment]
Thanks, @chkr1011! 👍

**Comment by waliarubal** [comment]
The official update does not seem to be working with latest Visual Studio 2022 with Avalonia extension.

**Comment by omnjpa27516** [comment]
It seems this project is dead, any alternatives to recommend?

**Comment by grochocki** [comment]
@omnjpa27516 Update with this change should now be available for VS2017, VS2019, and VS2022 with version 3.2208.1.

**Pull request merged**
