### PR TITLE
Feature request: XAML Styler extension for Visual Studio for Mac 2019

### PR DESCRIPTION
**Pull request by Saratsin**
Extension for the latest Visual Studio for Mac 2019
See [related issue](https://github.com/Xavalon/XamlStyler/issues/135)
Features:
"Format Xaml" option in editor context menu and "Edit" tab when file with xaml extension is opened
Shortcut for Visual Studio for Mac at "Format Xaml" option: Command + Shift + I
Xaml formatting settings in Visual Studio for Mac preferences menu (See Preferences -> Other -> XamlStyler Options)
Several files formatting with "Batch Format Xaml" option: right click on project or solution folder in the solution pad and select "Batch Format Xaml" option from the context menu and you will format all the Xaml files inside your folder/solution by one click)

P.S. Many thanks to [Ben Lacey](https://github.com/benlacey) for the work he made for this plugin

### CODE REVIEW

**Comment by Saratsin** [comment]
Need discuss about AppVeyor build. It can't now build VisualStudioForMac project, because, as I got it, it has no reference to the MonoDevelop or smth like this

**Comment by adamhill** [comment]
@Saratsin  Dude, you **rock**! Thanks for the PR. 

I was about to try take a stab at trying to fix this. You have the thanks of 1000' s of VS Mac teams everywhere!

**Comment by adamhill** [comment]
Should this release pick up the Settings.XamlStyler at the same level of the .sln file. By default on VS 8.0.5, Mojave 10.14.4 It does not by default. I also tried adding './Settings.XamlStyler' explicitly to the file path entry field in the Settings to no avail. The file seems to work fine on the PC side. Any suggestions? 

I have attached the file in case it is a formatting problem in the file.(I had to rename it to a .txt for Github to allow me to upload, it is NOT that way on the filesystem)

Thanks,

[Settings.XamlStyler.txt](https://github.com/Xavalon/XamlStyler/files/3163256/Settings.XamlStyler.txt)

**Comment by NicoVermeir** [comment]
@Saratsin care to chime in? :)

**Comment by Saratsin** [comment]
Yeah, I will check it. I haven't been working with Xaml styler on Windows, so I think there're a lot of things to add/improve)

**Comment by Saratsin** [comment]
@adamhill this functionality wasn't implemented in this release for Mac extension. I think I'll transfer it as first feature, as it's really useful to synchronize the team during development

**Comment by adamhill** [comment]
Ok, new data. In a new instance of 2019 (one thats has a fresh install of XamlStyler, never configured) on the PC, Settings.XamlStyler is not getting picked up. (same file as above)

I have tried paths of:

- `Settings.XamlStyler`
- `./Settings.XamlStyler`
- `.\Settings.XamlStyler`
- And an absolute path of `C:\Users\<username>\dev\Mobile\PaycorEmployeeShared\Settings.XamlStyler`

When I get a chance I will run ProcMon and see whats files VS + XS are trying to open and are they being successful.

**Pull request merged**
