### PR TITLE
Make extension compatible with VS2022

### LINKED ISSUE #353: Visual Studio 2022 Support
We are excited to add support for Visual Studio 2022. However, due to a limitation preventing us from publishing split extensions to the marketplace, we are holding on a release. This is something we plan to resolve before VS2022 leaves preview.

**Update (11/17):** As we work to merge this change (#360), we've released [XAML Styler for Visual Studio 2022](https://marketplace.visualstudio.com/items?itemName=TeamXavalon.XAMLStyler2022) in preview in the marketplace.

### PR DESCRIPTION
**Pull request by virzak**
### Description:

Fixes #353 

### Checklist:
* [x] I have commented my code, particularly in hard-to-understand areas
* [x] My changes generate no new warnings
* [x] I have added tests that prove my fix is effective or that my feature works
* [x] New and existing unit tests pass locally with my changes
* [x] I have tested my changes by running the extension in VS2017
* [x] I have tested my changes by running the extension in VS2019
* [x] I have tested my changes by running the extension in VS2022
* [x] If changes to the [documentation](https://github.com/Xavalon/XamlStyler/wiki) are needed, I have noted this in the description above

### CODE REVIEW

**Comment by virzak** [comment]
Following the [upgrade instructions](https://www.youtube.com/watch?v=L8b3kFriwCs) for upgrading the extension, I'm running into an issue with VS2022

```
SetSite failed for package [StylerPackage]Source: 'XamlStyler.Extension.Windows' Description: Method not found: 'EnvDTE.Events EnvDTE._DTE.get_Events()'.
System.MissingMethodException: Method not found: 'EnvDTE.Events EnvDTE._DTE.get_Events()'.
   at Xavalon.XamlStyler.Extension.Windows.StylerPackage.AddCommandHandlers()
   at Xavalon.XamlStyler.Extension.Windows.StylerPackage.&lt;InitializeAsync&gt;d__12.MoveNext()
```

Upgrading a single package causes compile errors.

```
error CS0433: The type 'IVsUIShell' exists in both 'Microsoft.VisualStudio.Interop, Version=17.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' and 'Microsoft.VisualStudio.Shell.Interop, Version=7.1.40304.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
```

If all packages are upgraded to their latest versions, I then get VS2019 errors:

```
    CreateInstance failed for package [StylerPackage]Source: 'mscorlib' Description: Could not load file or assembly 'Microsoft.VisualStudio.Shell.15.0, Version=17.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.VisualStudio.Shell.15.0, Version=17.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
File name: 'Microsoft.VisualStudio.Shell.15.0, Version=17.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
```

Anyone has a suggestion?

cc @madskristensen

**Comment by virzak** [comment]
"... even if you have a regular command and you do text changes in you before query status ... you will need to do the split"

https://youtu.be/-PKIPTW6km0?t=5688

Doesn't seem like spit can be avoided here:

https://github.com/Xavalon/XamlStyler/blob/82b68c5007959a67f3c38f869c1c5a38375214a7/src/XamlStyler.Extension.Windows/StylerPackage.cs#L92-L93

The error was:

```
SetSite failed for package [StylerPackage]Source: 'XamlStyler.Extension.Windows' Description: Method not found: 'Void EnvDTE._dispCommandEvents_BeforeExecuteEventHandler..ctor(System.Object, UIntPtr)'.
System.MissingMethodException: Method not found: 'Void EnvDTE._dispCommandEvents_BeforeExecuteEventHandler..ctor(System.Object, UIntPtr)'.
   at Xavalon.XamlStyler.Extension.Windows.StylerPackage.AddCommandHandlers()
   at Xavalon.XamlStyler.Extension.Windows.StylerPackage.&lt;InitializeAsync&gt;d__12.MoveNext()
```

**Comment by NicoVermeir** [comment]
Hi @virzak thanks a lot for your contribution, we appreciate it!
Allow us some time to look into the new extension model for VS2022 and how / if the marketplace can support multiple packages under one listing. We should be able to get back to you next week.

thanks again!

**Comment by jamers99** [comment]
Any update on this?
I've downloaded the vsix from the artifacts in the meantime: https://dev.azure.com/xavalon/XAML%20Styler/_build/results?buildId=401&view=artifacts&type=publishedArtifacts

**Comment by NicoVermeir** [comment]
@jamers99 not yet, sorry for the delay. I'll look into it tomorrow, thanks for the push!

**Comment by alski** [comment]
@jamers99 Thanks for the suggestion, I am also now running from the same VSIX

**Comment by shawyunz** [comment]
Any update on this? Will fix #344

**Comment by Chips1234** [comment]
Are there any updates with this PR? Thanks

**Comment by NicoVermeir** [comment]
Thanks for the patience everyone. 
We have discussed this and have decided to not push a VS2022 version to the marketplace just yet. We would have to create a new entry in the marketplace for this version and would prefer not to. We want to wait and see how / if the Visual Studio gallery will be updated to support multiple vsix files for the same extension. 

For now the download from the artifacts can be used for VS2022 support:
https://dev.azure.com/xavalon/XAML%20Styler/_build/results?buildId=401&view=artifacts&type=publishedArtifacts

**Comment by Chips1234** [comment]
Ah okay, thanks for the update.

**Comment by grochocki** [comment]
Thanks, @virzak! I've been debugging this branch, and I need to make a few changes to prep for release, so merging this into a feature branch to capture these changes and will add a few deltas there.

**Pull request merged**
