### PR TITLE
Add support for Rider 2024.3

### LINKED ISSUE #514: Rider 2024.3 is out and XamlStyler rider plugin needs an update
**Is your feature request related to a problem? Please describe.**
I can't use XamlStyler with the new version of rider. 

**Describe the solution you'd like**
Rider plugin in needs an update to work with the new rider version 

**Describe alternatives you've considered**
For now i can use the Cli version of XamlStyler with a file watcher

**Additional context**
billede

I would like to help but i have no clue how to

### PR DESCRIPTION
**Pull request by johanneswolfgruber**
### Description:

Fixes #514

### Checklist:
* [ ] I have commented my code, particularly in hard-to-understand areas
* [x] My changes generate no new warnings
* [ ] I have added tests that prove my fix is effective or that my feature works
* [ ] New and existing unit tests pass locally with my changes
* [ ] I have tested my changes by running the extension in VS2017
* [ ] I have tested my changes by running the extension in VS2019
* [ ] I have tested my changes by running the extension in VS2022
* [ ] If changes to the [documentation](https://github.com/Xavalon/XamlStyler/wiki) are needed, I have noted this in the description above

### CODE REVIEW

**Comment by JohnTraDolta** [comment]
After some investigation i can see that in RiderXamlStylerHost.cs the SolutionComponentAttribute is obsolete and it should be used with the Instantiation enum. 

Not sure what the right option is here but `Instantiation.DemandAnyThreadSafe` should be the best option. 
So maybe 
``` csharp
...
   [SolutionComponent(Instantiation.DemandAnyThreadSafe)]
    public class RiderXamlStylerHost
    {
...
```

**Comment by johanneswolfgruber** [comment]
Thanks, I also just saw that and will try if that fixes the build issue.

**Comment by johanneswolfgruber** [comment]
I think I also need to update the JDK version

`The Java configuration specifies sourceCompatibility='17' but IntelliJ Platform '2024.3' requires sourceCompatibility='21'`

**Comment by johanneswolfgruber** [comment]
Sorry, there is still an issue:

`import com.jetbrains.rider.ideaInterop.fileTypes.xaml.XamlLanguage` cannot be resolved.

I could not find anything about it for now, will keep looking, but if someone knows what to do, help is appreciated.

**Comment by JohnTraDolta** [comment]
I will try and see if i can find anything

**Comment by johanneswolfgruber** [comment]
I think it should work now. I rolled back the update of the Intellij Platform version from 2.1.0 to 2.0.1, as there seem to be breaking changes. I will create a separate issue for upgrading to 2.1.0. I tested the artifacts on Rider 2024.3 on windows and it seemed to work. Sorry for the number of commits, I can squash before we merge if you want me to. As this is my first PR here, I do not know how you handle this. Just let me know, thanks.

**Comment by NicoVermeir** [comment]
> I think it should work now. I rolled back the update of the Intellij Platform version from 2.1.0 to 2.0.1, as there seem to be breaking changes. I will create a separate issue for upgrading to 2.1.0. I tested the artifacts on Rider 2024.3 on windows and it seemed to work. Sorry for the number of commits, I can squash before we merge if you want me to. As this is my first PR here, I do not know how you handle this. Just let me know, thanks.

no worries, and thanks a ton for contributing. I'll pull your branch and do some manual tests locally. stay tuned! :)

**Comment by johanneswolfgruber** [comment]
> > I think it should work now. I rolled back the update of the Intellij Platform version from 2.1.0 to 2.0.1, as there seem to be breaking changes. I will create a separate issue for upgrading to 2.1.0. I tested the artifacts on Rider 2024.3 on windows and it seemed to work. Sorry for the number of commits, I can squash before we merge if you want me to. As this is my first PR here, I do not know how you handle this. Just let me know, thanks.
> 
> no worries, and thanks a ton for contributing. I'll pull your branch and do some manual tests locally. stay tuned! :)

thank you very much! :)

**Comment by johanneswolfgruber** [comment]
> i did some testing, and i think the `[SolutionComponent(JetBrains.Application.Parts.Instantiation.DemandAnyThreadSafe)]` is not the right one, as it breaks format on save. I got it to work with `[SolutionComponent(JetBrains.Application.Parts.Instantiation.ContainerSyncPrimaryThread)]`
> 
> I also want to let you know, that i know nothing about which one is the right one and i found out by trail and error :)

Thanks for investigating this. I missed it the first time around, but can confirm that format on save is working now.

**Comment by NicoVermeir** [comment]
@maartenba do you happen to have any insights on the Solution Component?

**Review by NicoVermeir — APPROVED** [review]
looks good to me 👍

**Comment by johanneswolfgruber** [comment]
> Not 100% sure based on the XamlStyler codebase but I believe `[ShellComponent(Instantiation.ContainerSyncPrimaryThread)]` is the one to go with. `[ShellComponent(Instantiation.ContainerAsyncPrimaryThread)]` may work (and be a little friendlier to the UI thread) but looking at what happens in code the sync version seems safer.

Thanks a lot for the insights, just to be sure, you meant SolutionComponent instead of ShellComponent, right? I was not able to find `ShellComponent` and it was `SolutionComponent` before.

**Pull request merged**
